Please fill out the information of your group!

| <p style="text-align: center;">First Name</p>  | <p style="text-align: center;">Family Name</p> | Matr.-No. |
| ---------------------------------------------- | ---------------------------------------------- | -------- |
| <p style="text-align: left">*EDIT!*</p>| <p style="text-align: left">*EDIT!*</p> | *EDIT!* |
| <p style="text-align: left">*EDIT!*</p>| <p style="text-align: left">*EDIT!*</p> | *EDIT!* |


<h2 style="text-align: center">344.075 KV: Natural Language Processing (WS2022/23)</h2>
<h1 style="color:rgb(0,120,170)">Assignment 3</h1>
<h2 style="color:rgb(0,120,170)">Document Classification with PyTorch and BERT</h2>

<b>Terms of Use</b><br>
This  material is prepared for educational purposes at the Johannes Kepler University (JKU) Linz, and is exclusively provided to the registered students of the mentioned course at JKU. It is strictly forbidden to distribute the current file, the contents of the assignment, and its solution. The use or reproduction of this manuscript is only allowed for educational purposes in non-profit organizations, while in this case, the explicit prior acceptance of the author(s) is required.

**Authors:** Navid Rekab-saz, Oleg Lesota<br>


<h2>Table of contents</h2>
<ol>
    <a href="#section-general-guidelines"><li style="font-size:large;font-weight:bold">General Guidelines</li></a>
    <a href="#section-tensorboard"><li style="font-size:large;font-weight:bold">Bonus Task: Logging and Publishing Experiment Results (2 extra point)</li></a>
    <a href="#section-taskA"><li style="font-size:large;font-weight:bold">Task A: Document Classification with PyTorch (25 points)</li></a>
    <a href="#section-taskB"><li style="font-size:large;font-weight:bold">Task B: Document Classification with BERT (15 points)</li></a>
    
    
</ol>

<a name="section-general-guidelines"></a><h2 style="color:rgb(0,120,170)">General Guidelines</h2>

### Assignment objective
This assignment aims to provide the necessary practices for learning the principles of deep learning programing in NLP using PyTorch. To this end, Task A provides the space for becoming fully familiar with PyTorch programming by implementing a "simple" document (sentence) classification model with PyTorch, and Task B extends this classifier with a BERT model. As the assignment requires working with PyTorch and Huggingface Transformers, please familiarize yourself with these libraries using any possible available teaching resources in particular the libraries' documentations. The assignment has in total **40 points**, and also offers **2 extra points** which can cover any missing point.

This Notebook encompasses all aspects of the assignment, namely the descriptions of tasks as well as your solutions and reports. Feel free to add any required cell for solutions. The cells can contain code, reports, charts, tables, or any other material, required for the assignment. Feel free to provide the solutions in an interactive and visual way! 

Please discuss any unclear point in the assignment in the provided forum in MOODLE. It is also encouraged to provide answers to your peer's questions. However when submitting a post, keep in mind to avoid providing solutions. Please let the tutor(s) know shall you find any error or unclarity in the assignment.


### Libraries & Dataset

The assignment should be implemented with recent versions of `Python`, `PyTorch` and, `transformers`. Any standard Python library can be used, so far that the library is free and can be simply installed using `pip` or `conda`. Examples of potentially useful libraries are `scikit-learn`, `numpy`, `scipy`, `gensim`, `nltk`, `spaCy`, and `AllenNLP`. Use the latest stable version of each library.

To conduct the experiments, we use a subset of the `HumSet` dataset [1] (https://blog.thedeep.io/humset/). `HumSet` is created by the DEEP (https://www.thedeep.io) project – an open source platform which aims to facilitate processing of textual data for international humanitarian response organizations. The platform enables the classification of text excerpts, extracted from news and reports into a set of domain specific classes. The provided dataset contains the classes (labels) referring to the humanitarian sectors like agriculture, health, and protection. The dataset contains an overall number of 17,301 data points. 

Download the dataset from the Moodle page of the course.

the provided zip file consists of the following files:
- `thedeep.subset.train.txt`: Train set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.validation.txt`: Validation set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.test.txt`: Test set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.label.txt`: Captions of the labels.
- `thedeep.ToU.txt`: Terms of use of the dataset.

[1] HumSet: Dataset of Multilingual Information Extraction and Classification for Humanitarian Crises Response
*Selim Fekih, Nicolo' Tamagnone, Benjamin Minixhofer, Ranjan Shrestha, Ximena Contla, Ewan Oglethorpe and Navid Rekabsaz.* 
In Findings of the 2022 Conference on Empirical Methods in Natural Language Processing (Findings of EMNLP), December 2022.


### Submission

Each group should submit the following two files:

- One Jupyter Notebook file (`.ipynb`), containing all the code, results, visualizations, etc. **In the submitted Notebook, all the results and visualizations should already be present, and can be observed simply by loading the Notebook in a browser.** The Notebook must be self-contained, meaning that (if necessary) one can run all the cells from top to bottom without any error. Do not forget to put in your names and student numbers in the first cell of the Notebook. 
- The HTML file (`.html`) achieved from exporting the Jupyter Notebook to HTML (Download As HTML).

You do not need to include the data files in the submission.



<a name="section-tensorboard"></a><h2 style="color:rgb(0,120,170)">Bonus Task: Logging and Publishing Experiment Results (2 extra point)</h2>

In all experiments of this assignment, use any experiment monitoring tool like [`TensorBoard`](https://www.tensorflow.org/tensorboard), [`wandb`](https://wandb.ai) to log and store all useful information about the training and evaluation of the models. Feel free to log any important aspect in particular the changes in evaluation results on validation, in training loss, and in learning rate.

After finalizing all experiments and cleaning any unnecessary experiment, **provide the URL to the results monitoring page below**.

For instance if using [`TensorBoard.dev`](https://tensorboard.dev), you can run the following command in the folder of log files: `tensorboard dev upload --name my_exp --logdir path/to/output_dir`, and take the provided URL to the TensorBoard's console.


**URL :** *EDIT!*

<a name="section-taskA"></a><h2 style="color:rgb(0,120,170)">Task A: Document Classification with PyTorch (25 points)</h2>

The aim of this task is identical to the one of Assignment 2 - Task B, namely to design a document classification model that exploits pre-trained word embeddings. It is of course allowed to use the preprocessed text, the dictionary, or any other relevant code or processings, done in the previous assignments.

In this task, you implement a document classification model using PyTorch, which given a document/sentence (consisting of a set of words) predicts the corresponding class. Before getting started with coding, have a look at the <a href="#section-tensorboard">optional task</a>, as you may want to already include `Tensorboard` in the code. The implementation of the classifier should cover the points below.

**Preprocessing and dictionary (1 point):** Following previous assignments, load the train, validation, and test datasets, apply necessary preprocessing steps, and create a dictionary of words. 

**Data batching (4 points):** Using the dictionary, create batches for any given dataset (train/validation/test). Each batch is a two-dimensional matrix of *batch-size* to *max-document-length*, containing the IDs of the words in the corresponding documents. *Batch-size* and *max-document-length* are two hyper-parameters and can be set to any appropriate values (*Batch-size* must be higher than 1 and *max-document-length* at least 50 words). If a document has more than *max-document-length* words, only the first *max-document-length* words should be kept.

**Word embedding lookup (2 point):** Using `torch.nn.Embedding`, create a lookup for the embeddings of all the words in the dictionary. The lookup is in fact a matrix, which maps the ID of each word to the corresponding word vector. Similar to Assignment 2, use the pre-trained vectors of a word embedding model (like word2vec or GloVe) to initialize the word embeddings of the lookup. Keep in mind that the embeddings of the words in the lookup should be matched with the correct vector in the pretrained word embedding. If the vector of a word in the lookup does not exist in the pretrained word embeddings, the corresponding vector should be initialized randomly. 

**Model definition (3 points):** Define the class `ClassificationAverageModel` as a PyTorch model. In the initialization procedure, the model receives the word embedding lookup, and includes it in the model as model's parameters. These embeddings parameters should be trainable, meaning that the word vectors get updated during model training. Feel free to add any other parameters to the model, which might be necessary for accomplishing the functionalities explained in the following.

**Forward function (5 points):** The forward function of the model receives a batch of data, and first fetches the corresponding embeddings of the word IDs in the batch using the lookup. Similar to Assignment 2, the embedding of a document is created by calculating the *element-wise mean* of the embeddings of the document's words. Formally, given the document $d$, consisting of words $\left[ v_1, v_2, ..., v_{|d|} \right]$, the document representation $\mathbf{e}_d$ is defined as:

<center><div>$\mathbf{e}_d = \frac{1}{|d|}\sum_{i=1}^{|d|}{\mathbf{e}_{v_i}}$</div></center>

where $\mathbf{e}_{v}$ is the vector of the word $v$, and $|d|$ is the length of the document. An important point in the implementation of this formula is that the documents in the batch might have different lengths and therefore each document should be divided by its corresponding $|d|$. Finally, this document embedding is utilized to predict the probability of the output classes, done by applying a linear transformation from the embeddings size to the number of classes, followed by Softmax. The linear transformation also belongs to the model's parameters and will be learned in training.

**Loss Function and optimization (2 point):** The loss between the predicted and the actual classes is calculated using Negative Log Likelihood or Cross Entropy. Update the model's parameters using any appropriate optimization mechanism such as Adam.

**Early Stopping (2 points):** After each epoch, evaluate the model on the *validation set* using accuracy. If the evaluation result (accuracy) improves, save the model as the best performing one so far. If the results are not improving after a certain number of evaluation rounds (set as another hyper-parameter) or if training reaches a certain number of epochs, terminate the training procedure. 

**Test Set Evaluation (1 point):** After finishing the training, load the (already stored) best performing model, and use it for class prediction on the test set.

**Reporting (1 point):** During loading and processing the collection, provide sufficient information and examples about the data and the applied processing steps. Report the results of the best performing model on the validation and test set in a table.

**Overall functionality of the training procedure (4 point).**


In [2]:
# Preprocessing and dictionary (1 point): 
# Following previous assignments, load the train, validation, and test datasets, 
# apply necessary preprocessing steps, and create a dictionary of words. 

In [3]:
import os
import glob
import re
import itertools
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import MWETokenizer
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.corpus import stopwords
from collections import Counter
import itertools
import random
import torch
from torch import nn

In [4]:
# helper functions

# function to split the data into text and labels
def split_into_texts_and_labels(data):
    labels = []
    texts = data.split('\n')
    texts = [text for text in texts if len(text)>0]
    for i, text in enumerate(texts):
        try:
            nr = int(text[-1])
            labels.append(text[-1])
            texts[i] = ''.join(list(text)[:-2])
        except:
            break
    return texts, labels


# apply some basic preprocessing methods
# such as replacing all the dates and numbers with a special token 
# and removing special characters
def perform_basic_preprocessing(text):
    text = text.lower()

    # replace the dates with <date>
    for d in re.finditer('\d{1,2}[/-]\d{1,2}[/-]\d{2,4}', text):
        text = text.replace(str(d.group()), '<date>')

    for d in re.finditer(r'(\d{1,2}[\s]?|\d{1,2}[\s]?th[\s]?)?(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[\s-]?(\d{1,2})?[,\s-]?[\s]?\d{4}', text, re.I|re.M):
        text = text.replace(str(d.group()), '<date>')

    for d in re.finditer(r'(\d{1,2}|\d{1,2}[\s]?th)[\s]?(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)', text, re.I|re.M):  
        text = text.replace(str(d.group()), '<date>')

    for d in re.finditer(r'\d{1,2}[/-]\d{4}', text, re.M|re.I):
        text = text.replace(str(d.group()), '<date>')
        
    # replace the remaining numbers with <num>
    text = re.sub('[0-9]*[[,.]?[0-9]+]*', '<num>', text)
    
    # remove all special characters besides <>
    text = re.sub('([^a-z<>])+', ' ', text)

    return text

# split the text into single tokens
def perform_tokenization(text):
    stop_words = set(stopwords.words('english'))
    lemmatizer = WordNetLemmatizer()

    # define tokenizer for special tokens
    tokenizer = MWETokenizer([('<', 'num', '>'), ('<', 'date', '>')])
    tokens = tokenizer.tokenize(nltk.word_tokenize(text))
    
    # remove stop words
    tokens = [token for token in tokens if not token in stop_words]
    # perform lemmatization
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return tokens

In [5]:
# Load the train, validation, and test sets. 
files = glob.glob(os.path.join('nlp2023_24_data', '**', '*'))

for file in files:
    if os.path.basename(file).__contains__('train'):
        with open(file, 'r') as fh:
            train_data = fh.read()
    elif os.path.basename(file).__contains__('test'):
        with open(file, 'r') as fh:
            test_data = fh.read()
    elif os.path.basename(file).__contains__('validation'):
        with open(file, 'r') as fh:
            val_data = fh.read()
    elif os.path.basename(file).__contains__('labels'):
        with open(file, 'r') as fh:
            labels = fh.read()

# split each data file into a list of texts and a list of their corresponding labels
train_texts, train_labels = split_into_texts_and_labels(train_data)
val_texts, val_labels = split_into_texts_and_labels(val_data)
test_texts, test_labels = split_into_texts_and_labels(test_data)
# print(len(train_texts))

# get a list of tokens (tokens_per_text) for each preprocessed text in the training data 
tokens_per_text_train = []
for text in train_texts:
    # print(text)
    tokens_per_text_train.append(perform_tokenization(perform_basic_preprocessing(text)))


# generate one dictionary containing all tokens that appear accross all texts 
# and count the number of their overall occurences
word_dict = dict(Counter(list(itertools.chain(*tokens_per_text_train))))
# sort the dictionary by the number of word occurences
word_dict = dict(sorted(word_dict.items(), key=lambda x:x[1], reverse=True))

threshold = 100 
smaller_word_dict = {k:v for (k,v) in word_dict.items() if v > threshold}

/tmp/ipykernel_256214/4152795208.py:38: FutureWarning: Possible nested set at position 7
  text = re.sub('[0-9]*[[,.]?[0-9]+]*', '<num>', text)


In [6]:
print(len(train_texts))

12110


In [6]:
'''
Data batching (4 points): 
Using the dictionary, create batches for any given dataset (train/validation/test). 
Each batch is a two-dimensional matrix of batch-size to max-document-length, 
containing the IDs of the words in the corresponding documents. 
Batch-size and max-document-length are two hyper-parameters and can be set to any appropriate values 
(Batch-size must be higher than 1 and max-document-length at least 50 words). 
If a document has more than max-document-length words, only the first max-document-length words should be kept.
'''

# two hyperparams
bs = 16 # 32, 64...
max_doc_len = 80 

# smaller_word_dict => key is word, value is occurence
# can add OOV to smaller_word_dict
smaller_word_dict['oov'] = 0

def get_batch(bs, max_doc_len, dataset, word_dict):
    
    batch = np.zeros((bs, max_doc_len))
    current_pos = 0
    mult_factor = 0
    
    for i, data_point in enumerate(dataset):
        if i+bs >= len(dataset):
            break
        if i % bs == 0 and i > 0:
            current_pos += bs
            yield torch.IntTensor(batch), current_pos
            mult_factor += 1
        
        counter = itertools.count(0)
        # discard words that are not in the word_dict
        doc_word_ids = [list(word_dict).index(word) for word in (perform_tokenization(perform_basic_preprocessing(data_point))) if word in word_dict.keys() and next(counter) < max_doc_len]
        
        if len(doc_word_ids) < max_doc_len:
            # print(np.array(doc_word_ids).shape)
            # print(np.full((max_doc_len-len(doc_word_ids)), list(word_dict).index('oov')).shape)
            batch[i-(bs*mult_factor)] = np.concatenate((np.array(doc_word_ids), np.full((max_doc_len-len(doc_word_ids)), list(word_dict).index('oov'))), axis=0)
        else:
            batch[i-(bs*mult_factor)] = np.array(doc_word_ids)

In [8]:
'''
Word embedding lookup (2 point): Using torch.nn.Embedding, create a lookup for the embeddings of all the words 
in the dictionary. The lookup is in fact a matrix, which maps the ID of each word to the corresponding word vector. 
Similar to Assignment 2, use the pre-trained vectors of a word embedding model (like word2vec or GloVe)
to initialize the word embeddings of the lookup. Keep in mind that the embeddings of the words in the lookup 
should be matched with the correct vector in the pretrained word embedding. If the vector of a word in the lookup 
does not exist in the pretrained word embeddings, the corresponding vector should be initialized randomly.
'''

embeddings_dict = {}
with open('glove.6B.300d.txt', 'r') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], 'float32')
        embeddings_dict[word] = vector
# print(embeddings_dict['dog']) 

# can also create a new dictionary where we map each word to an index
# word2idx = {w:i for i,w in enumerate(smaller_word_dict.keys())}
        
embed_lookup = nn.Embedding(len(smaller_word_dict), 300)
pretrained_weights = []
for word in smaller_word_dict.keys():
    try:
        pretrained_weights.append(embeddings_dict[word])
    except:
        pretrained_weights.append(np.random.normal(0, 0.5, 300))

embed_lookup.weight.data.copy_(torch.from_numpy(np.array(pretrained_weights)))

ids = [list(smaller_word_dict).index(word) for word in smaller_word_dict.keys()]
word_vecs = embed_lookup(torch.LongTensor(ids)) 

In [9]:
# print(np.random.normal(0, 1, 300))

In [10]:
# print(word_vecs[0])

In [11]:
'''
Model definition (3 points): Define the class ClassificationAverageModel as a PyTorch model. 
In the initialization procedure, the model receives the word embedding lookup, 
and includes it in the model as model's parameters. These embeddings parameters should be trainable, 
meaning that the word vectors get updated during model training. Feel free to add any other parameters to the model, 
which might be necessary for accomplishing the functionalities explained in the following.
'''

'''
Forward function (5 points): The forward function of the model receives a batch of data, 
and first fetches the corresponding embeddings of the word IDs in the batch using the lookup. 
Similar to Assignment 2, the embedding of a document is created by calculating the element-wise mean of 
the embeddings of the document's words. Formally, given the document 𝑑, consisting of words [𝑣1,𝑣2,...,𝑣|𝑑|], 
the document representation 𝐞𝑑

is defined as:
𝐞𝑑=1|𝑑|∑|𝑑|𝑖=1𝐞𝑣𝑖

where 𝐞𝑣
is the vector of the word 𝑣, and |𝑑| is the length of the document. 
An important point in the implementation of this formula is that the documents in the batch might
have different lengths and therefore each document should be divided by its corresponding |𝑑|. 
Finally, this document embedding is utilized to predict the probability of the output classes, 
done by applying a linear transformation from the embeddings size to the number of classes, followed by Softmax. 
The linear transformation also belongs to the model's parameters and will be learned in training.'''


class ClassificationAverageModel(nn.Module):
    
    def __init__(self, lookup, docs, bs):
        super(ClassificationAverageModel, self).__init__()
        self.lookup = nn.Parameter(lookup)
        self.lookup.requires_grad = True
        
        self.bs = bs
        self.docs = docs
        
        self.linear = nn.Linear(300, 12)
        self.softmax = nn.Softmax(dim=1)
        
        
    def forward(self, batch, current_pos):
     
        e_ds = []
        for i, doc_ids in enumerate(batch):
            doc_embeds = self.lookup[doc_ids.tolist()] 
            e_ds.append(np.sum(doc_embeds.tolist(), axis=0)/len(self.docs[current_pos-self.bs+i]))
        
        # return self.softmax(self.linear(torch.from_numpy(np.array(e_ds)).float()))
        return self.linear(torch.from_numpy(np.array(e_ds)).float())
    
c = ClassificationAverageModel(word_vecs, train_texts, bs)
for b, counter in get_batch(bs, max_doc_len, train_texts, smaller_word_dict):
    print(c.forward(b, counter))
    break

tensor([[-2.1740e-02, -1.1853e-01, -5.0232e-02, -6.1991e-02, -9.4787e-02,
         -2.1333e-01, -7.5989e-02,  1.4220e-01, -4.0274e-02, -9.1852e-02,
         -2.3542e-02,  2.0936e-02],
        [ 4.2973e-02, -5.5664e-02,  3.2067e-03, -6.0115e-02,  2.7030e-02,
         -6.0373e-03, -2.7182e-02,  5.5100e-02, -5.5786e-02, -3.3384e-02,
          1.5456e-02, -4.7657e-03],
        [ 2.4145e-02, -6.7838e-02, -1.1615e-02, -5.6722e-02, -4.0764e-03,
         -4.1419e-02, -3.0782e-02,  6.5439e-02, -5.2047e-02, -4.0955e-02,
          1.2831e-02,  4.5219e-03],
        [ 2.5934e-02, -6.4447e-02, -1.1385e-02, -5.6997e-02, -7.7177e-03,
         -4.5333e-02, -3.6238e-02,  6.7079e-02, -5.2839e-02, -4.3493e-02,
          1.2493e-02, -6.8279e-04],
        [ 4.4054e-02, -5.4645e-02,  1.0365e-02, -5.9963e-02,  3.1558e-02,
          3.8349e-03, -1.9458e-02,  4.7000e-02, -5.0976e-02, -2.3565e-02,
          2.4668e-02, -1.3767e-03],
        [ 1.0293e-02, -7.8010e-02, -1.4640e-02, -5.3300e-02, -1.5331e-02,
      

In [13]:
'''
Loss Function and optimization (2 point): 
The loss between the predicted and the actual classes is calculated using Negative Log Likelihood or Cross Entropy.
Update the model's parameters using any appropriate optimization mechanism such as Adam.
'''

'''
Early Stopping (2 points): After each epoch, evaluate the model on the validation set 
using accuracy. If the evaluation result (accuracy) improves, save the model as 
the best performing one so far. If the results are not improving after a certain 
number of evaluation rounds (set as another hyper-parameter) or if training reaches a 
certain number of epochs, terminate the training procedure.
''' 

model = ClassificationAverageModel(word_vecs, train_texts, bs)
loss_fct = nn.CrossEntropyLoss() # should already have softmax???, nn.NLLLoss()
optim = torch.optim.Adam(model.parameters(), 0.001)
nr_epochs = 100
count = 0
old_acc = 0

for epoch in range(nr_epochs):
    for batch, current_pos in get_batch(bs, max_doc_len, train_texts, smaller_word_dict):
        optim.zero_grad()
        out = model(batch, current_pos)
        labels = train_labels[current_pos-bs:current_pos]
        loss = loss_fct(out, torch.tensor(np.array(labels).astype('int')))
        loss.backward()
        optim.step()
    if epoch % 20 == 0:
        print(loss)
    
    # early stopping at the end of every epoch
    acc = 0
    nr_batches = 0
    with torch.no_grad():
        for val_batch, val_current_pos in get_batch(bs, max_doc_len, val_texts, smaller_word_dict):
            out = model(val_batch, val_current_pos)
            # get max of out
            pred = torch.argmax(out, dim=1)
            acc += (torch.sum(pred == torch.tensor(np.array(val_labels[val_current_pos-bs:val_current_pos]).astype('int'))).item() / bs)
            nr_batches += 1
        acc /= nr_batches
        # print(acc)
        count +=1
        if acc > old_acc:
            old_acc = acc
            print(acc)
            # save_model
            # torch.save(model.state_dict(), PATH)
            torch.save(model.state_dict(), 'best_model.pth')
            count = 0
        if count > 10:
            # end training
            # break  
            print('Problem')

tensor(2.0234, grad_fn=<NllLossBackward0>)
0.35209627329192544
0.3684006211180124
0.3815993788819876
0.3951863354037267
0.4041149068322981
0.4079968944099379
0.4091614906832298
0.41459627329192544
0.42080745341614906
0.4231366459627329
0.4254658385093168
0.4309006211180124
0.4359472049689441
0.4394409937888199
0.4452639751552795
0.4495341614906832
0.45846273291925466
0.46195652173913043
0.4658385093167702
0.4720496894409938
tensor(1.5143, grad_fn=<NllLossBackward0>)
0.47787267080745344
0.4813664596273292
0.4871894409937888
0.49145962732919257
0.4937888198757764
0.49767080745341613
0.5007763975155279
0.5046583850931677
0.5108695652173914
0.5124223602484472
0.514751552795031
0.5182453416149069
0.5201863354037267
0.5232919254658385
0.5263975155279503
0.529891304347826
0.5349378881987578
0.5357142857142857
0.5372670807453416
tensor(1.2599, grad_fn=<NllLossBackward0>)
0.5392080745341615
0.5415372670807453
0.5438664596273292
0.5442546583850931
0.5461956521739131
0.5485248447204969
0.54891304

In [14]:
# Test Set Evaluation (1 point): After finishing the training, load the (already stored) best performing model, and use it for class prediction on the test set.
# model = TheModelClass(*args, **kwargs)
# model.load_state_dict(torch.load(PATH))
# model.eval()
model = ClassificationAverageModel(word_vecs, test_texts, bs)
model.load_state_dict(torch.load('best_model.pth'))
model.eval()
for test_batch, test_current_pos in get_batch(bs, max_doc_len, test_texts, smaller_word_dict):
            out = model(test_batch, test_current_pos)
            # get max of out
            pred = torch.argmax(out, dim=1)
            print(pred)
            print(test_labels[test_current_pos-bs:test_current_pos])
            
# Reporting (1 point): During loading and processing the collection, provide sufficient information and examples about the data and the applied processing steps. Report the results of the best performing model on the validation and test set in a table.
# TODO TODO

tensor([4, 4, 3, 9, 4, 1, 3, 3, 0, 4, 4, 3, 4, 9, 2, 4])
['8', '9', '3', '9', '8', '1', '3', '3', '0', '1', '4', '3', '4', '9', '2', '4']
tensor([4, 4, 1, 3, 4, 9, 4, 0, 3, 9, 9, 9, 4, 9, 4, 4])
['4', '4', '1', '5', '4', '9', '4', '5', '3', '0', '9', '9', '4', '9', '4', '4']
tensor([3, 9, 3, 9, 4, 8, 9, 9, 4, 9, 4, 9, 0, 3, 9, 4])
['8', '2', '3', '4', '4', '8', '9', '9', '4', '9', '4', '9', '0', '3', '9', '4']
tensor([2, 1, 3, 4, 3, 9, 0, 9, 3, 4, 9, 9, 4, 1, 0, 4])
['2', '1', '3', '4', '5', '9', '0', '9', '1', '4', '9', '9', '8', '4', '0', '4']
tensor([3, 1, 3, 8, 2, 4, 3, 9, 9, 9, 9, 4, 9, 4, 9, 4])
['3', '7', '3', '8', '2', '4', '3', '9', '9', '1', '9', '4', '0', '4', '9', '4']
tensor([9, 9, 3, 9, 0, 9, 9, 3, 9, 9, 3, 9, 9, 4, 9, 4])
['9', '0', '3', '9', '9', '1', '9', '3', '2', '9', '3', '9', '9', '4', '5', '4']
tensor([9, 4, 9, 4, 9, 0, 3, 0, 3, 4, 4, 2, 9, 1, 3, 3])
['9', '4', '9', '4', '6', '0', '3', '0', '3', '4', '4', '2', '1', '1', '3', '3']
tensor([4, 9, 3, 0, 4, 1, 0, 4, 9,

KeyboardInterrupt: 

<a name="section-taskB"></a><h2 style="color:rgb(0,120,170)">Task B: Document Classification with BERT (15 points)</h2>

This task aims to conduct the same document classification as Task A, but now by utilizing a pre-trained BERT model. Feel free to reuse any code from the previous task. The implementation of the classifier should cover the points below.

**Loading BERT model (2 points):** Use the `transformers` library from `huggingface` to load a (small) pre-trained BERT model. Select a BERT model according to your available resources. The available models can be found [here](https://huggingface.co/models) and [here](https://github.com/google-research/bert).

**BERT tokenization (3 points):** For training BERT models, we do not need to create a dictionary anymore, as a BERT model already contains an internal subword dictionary. Following the instruction in `transformers`'s documentation, tokenize the data using the BERT model.  

**Model definition and forward function (5 points):** Define the class **`ClassificationBERTModel`** as a PyTorch model. In the initialization procedure, the model receives the loaded BERT model and stores it as the model's parameter. The parameters of the BERT model should be trainable. The forward function of the model receives a batch of data, passes this batch to BERT, and achieves the corresponding document embeddings from the output of BERT. Similar to the previous task, the document embeddings are used for classification by linearly transforming document embeddings to the vectors with the number of classes, followed by applying Softmax.

**Training and overall functionality (3 points):** Train the model in a similar fashion to the previous task, namely with the proper loss function, optimization, and early stoping.

**Test Set Evaluation (1 point):** After finishing the training, load the (already stored) best performing model, and use it for class prediction on the test set.

**Reporting (1 point):** Report the results of the best performing model on the validation and test set in a table.


In [7]:
# Loading BERT model (2 points): 
# Use the transformers library from huggingface to load a (small) pre-trained BERT model. 
# Select a BERT model according to your available resources. The available models can be found here and here.

from transformers import BertModel, BertTokenizer
model = BertModel.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("prajjwal1/bert-tiny")

In [8]:
# BERT tokenization (3 points): 
# For training BERT models, we do not need to create a dictionary anymore, 
# as a BERT model already contains an internal subword dictionary. 
# Following the instruction in transformers's documentation, 
# tokenize the data using the BERT model.
import torch
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer = BertTokenizer.from_pretrained("prajjwal1/bert-tiny")
# print(tokenizer(train_texts[0], padding='max_length', truncation=True, max_length=80))      

def get_batch(bs, max_doc_len, dataset):
    
    batch = np.zeros((bs, max_doc_len))
    attention_mask = np.zeros((bs, max_doc_len))
    current_pos = 0
    mult_factor = 0
    
    for i, data_point in enumerate(dataset):
        if i+bs >= len(dataset):
            break
        if i % bs == 0 and i > 0:
            current_pos += bs
            yield torch.IntTensor(batch), torch.IntTensor(attention_mask), current_pos
            mult_factor += 1
     
        batch[i-(bs*mult_factor)] = tokenizer(data_point, padding='max_length', truncation=True, max_length=80)['input_ids']
        attention_mask[i-(bs*mult_factor)]= tokenizer(data_point, padding='max_length', truncation=True, max_length=80)['attention_mask']

In [ ]:
# TODO try different versions----------------------------------------------------------

In [10]:
# Model definition and forward function (5 points): 
# Define the class ClassificationBERTModel as a PyTorch model. 
# In the initialization procedure, the model receives the loaded BERT model 
# and stores it as the model's parameter. 
# The parameters of the BERT model should be trainable. 
# The forward function of the model receives a batch of data, passes this batch to BERT, 
# and achieves the corresponding document embeddings from the output of BERT. 
# Similar to the previous task, the document embeddings are used for classification
# by linearly transforming document embeddings to the vectors with the number of classes, 
# followed by applying Softmax.

class ClassificationBERTModel(nn.Module):
    
    def __init__(self, model, train=True):
        super(ClassificationBERTModel, self).__init__()
        self.model = model # nn.Parameter(model)
        if train:
            self.model.train()
            for param in self.model.parameters():
                param.requires_grad = True
        else:
            self.model.eval()
            for param in self.model.parameters():
                param.requires_grad = False
        # self.model.requires_grad = True
        self.linear = nn.Linear(128,12)# smaller cuz of tiny bert, else it is around 700
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, batch, attention_mask):
        # batch are the input_ids of the texts...
        # out = self.softmax(self.linear(self.model(batch)['pooler_output']))
        # TODO pooler_output???
        # print(self.model(batch)['pooler_output'].shape)
        out = self.linear(self.model(batch, attention_mask)['pooler_output'])
        return out
        
        # print(out['last_hidden_state'].shape, out['pooler_output'].shape)
        
# Training and overall functionality (3 points): 
# Train the model in a similar fashion to the previous task, 
# namely with the proper loss function, optimization, and early stoping.
    
model = BertModel.from_pretrained("bert-base-uncased") 
model = BertModel.from_pretrained("prajjwal1/bert-tiny") 

classifier = ClassificationBERTModel(model)
loss_fct = nn.CrossEntropyLoss() # nn.NLLLoss()
# lr=2e-5, eps=1e-8
optim = torch.optim.Adam(classifier.parameters(), 5e-5)

old_acc = 0
nr_epochs = 60
count = 0
bs = 16
max_doc_len = 80

for epoch in range(nr_epochs):
    for i, (batch, mask, current_pos) in enumerate(get_batch(bs, max_doc_len, train_texts)):
        optim.zero_grad()
        out = classifier.forward(batch, mask)          
        labels = train_labels[current_pos-bs:current_pos]            
        loss = loss_fct(out, torch.tensor(np.array(labels).astype('int')))
        loss.backward()
        optim.step()
    if epoch % 20 == 0:
        print(loss)
            
    # early stopping at the end of every epoch
    acc = 0
    nr_batches = 0
    with torch.no_grad():
        for val_batch, mask, val_current_pos in get_batch(bs, max_doc_len, val_texts):
            out = classifier(val_batch, mask)
            # get max of out
            pred = torch.argmax(out, dim=1)
            acc += (torch.sum(pred == torch.tensor(np.array(val_labels[val_current_pos-bs:val_current_pos]).astype('int'))).item() / bs)
            nr_batches += 1
        acc /= nr_batches
        count +=1
        if acc > old_acc:
            old_acc = acc
            print(acc)
            torch.save(classifier.state_dict(), 'best_model.pth')
            count = 0
        if count > 10:
            # end training
            # break  
            print('Problem') 
            
# TODO can add dropout, weight decay...if training loss decreases, but accuracy does not improve
# we overfit on the training data...

tensor(0.7083, grad_fn=<NllLossBackward0>)
0.7461180124223602
0.7833850931677019
0.7934782608695652
0.8043478260869565
Problem
Problem
Problem


KeyboardInterrupt: 

In [8]:
# Model definition and forward function (5 points): 
# Define the class ClassificationBERTModel as a PyTorch model. 
# In the initialization procedure, the model receives the loaded BERT model 
# and stores it as the model's parameter. 
# The parameters of the BERT model should be trainable. 
# The forward function of the model receives a batch of data, passes this batch to BERT, 
# and achieves the corresponding document embeddings from the output of BERT. 
# Similar to the previous task, the document embeddings are used for classification
# by linearly transforming document embeddings to the vectors with the number of classes, 
# followed by applying Softmax.

class ClassificationBERTModel(nn.Module):
    
    def __init__(self, model, train=True):
        super(ClassificationBERTModel, self).__init__()
        self.model = model # nn.Parameter(model)
        if train:
            self.model.train()
            for param in self.model.parameters():
                param.requires_grad = True
        else:
            self.model.eval()
            for param in self.model.parameters():
                param.requires_grad = False
        # self.model.requires_grad = True
        self.linear = nn.Linear(128,12)# smaller cuz of tiny bert, else it is around 700
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, batch, attention_mask):
        # batch are the input_ids of the texts...
        # out = self.softmax(self.linear(self.model(batch)['pooler_output']))
        # TODO pooler_output???
        # print(self.model(batch)['pooler_output'].shape)
        out = self.linear(self.model(batch, attention_mask)['pooler_output'])
        return out
        
        # print(out['last_hidden_state'].shape, out['pooler_output'].shape)
        
# Training and overall functionality (3 points): 
# Train the model in a similar fashion to the previous task, 
# namely with the proper loss function, optimization, and early stoping.
    
model = BertModel.from_pretrained("bert-base-uncased") 
model = BertModel.from_pretrained("prajjwal1/bert-tiny", hidden_dropout_prob=0.5) 

classifier = ClassificationBERTModel(model)
loss_fct = nn.CrossEntropyLoss() # nn.NLLLoss()
# lr=2e-5, eps=1e-8
optim = torch.optim.Adam(classifier.parameters(), lr=2e-5, weight_decay=1e-5)

old_acc = 0
nr_epochs = 60
count = 0
bs = 16
max_doc_len = 80

for epoch in range(nr_epochs):
    for i, (batch, mask, current_pos) in enumerate(get_batch(bs, max_doc_len, train_texts)):
        optim.zero_grad()
        out = classifier.forward(batch, mask)          
        labels = train_labels[current_pos-bs:current_pos]            
        loss = loss_fct(out, torch.tensor(np.array(labels).astype('int')))
        loss.backward()
        optim.step()
    if epoch % 20 == 0:
        print(loss)
            
    # early stopping at the end of every epoch
    acc = 0
    nr_batches = 0
    with torch.no_grad():
        for val_batch, mask, val_current_pos in get_batch(bs, max_doc_len, val_texts):
            out = classifier(val_batch, mask)
            # get max of out
            pred = torch.argmax(out, dim=1)
            acc += (torch.sum(pred == torch.tensor(np.array(val_labels[val_current_pos-bs:val_current_pos]).astype('int'))).item() / bs)
            nr_batches += 1
        acc /= nr_batches
        count +=1
        if acc > old_acc:
            old_acc = acc
            print(acc)
            torch.save(classifier.state_dict(), 'best_model.pth')
            count = 0
        if count > 10:
            # end training
            # break  
            print('Problem') 
            
# TODO can add dropout, weight decay...if training loss decreases, but accuracy does not improve
# we overfit on the training data...

tensor(1.9907, grad_fn=<NllLossBackward0>)
0.30240683229813664
0.46467391304347827
0.5512422360248447
0.6075310559006211
0.6630434782608695
0.687111801242236
0.703416149068323
0.7267080745341615
0.7294254658385093
0.7360248447204969
0.7383540372670807
0.7527173913043478
0.7678571428571429
0.7690217391304348
0.7787267080745341
tensor(0.5698, grad_fn=<NllLossBackward0>)
0.779891304347826
0.781832298136646
0.7833850931677019
tensor(0.3412, grad_fn=<NllLossBackward0>)
Problem


KeyboardInterrupt: 

In [9]:
# Model definition and forward function (5 points): 
# Define the class ClassificationBERTModel as a PyTorch model. 
# In the initialization procedure, the model receives the loaded BERT model 
# and stores it as the model's parameter. 
# The parameters of the BERT model should be trainable. 
# The forward function of the model receives a batch of data, passes this batch to BERT, 
# and achieves the corresponding document embeddings from the output of BERT. 
# Similar to the previous task, the document embeddings are used for classification
# by linearly transforming document embeddings to the vectors with the number of classes, 
# followed by applying Softmax.

class ClassificationBERTModel(nn.Module):
    
    def __init__(self, model, train=True):
        super(ClassificationBERTModel, self).__init__()
        self.model = model # nn.Parameter(model)
        if train:
            self.model.train()
            for param in self.model.parameters():
                param.requires_grad = True
        else:
            self.model.eval()
            for param in self.model.parameters():
                param.requires_grad = False
        # self.model.requires_grad = True
        self.linear = nn.Linear(128,12)# smaller cuz of tiny bert, else it is around 700
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, batch, attention_mask):
        # batch are the input_ids of the texts...
        # out = self.softmax(self.linear(self.model(batch)['pooler_output']))
        # TODO pooler_output???
        # print(self.model(batch)['pooler_output'].shape)
        out = self.softmax(self.linear(self.model(batch, attention_mask)['pooler_output']))
        return out
        
        # print(out['last_hidden_state'].shape, out['pooler_output'].shape)
        
# Training and overall functionality (3 points): 
# Train the model in a similar fashion to the previous task, 
# namely with the proper loss function, optimization, and early stoping.
    
model = BertModel.from_pretrained("bert-base-uncased") 
model = BertModel.from_pretrained("prajjwal1/bert-tiny", hidden_dropout_prob=0.5) 

classifier = ClassificationBERTModel(model)
loss_fct = nn.NLLLoss() # nn.NLLLoss()
# lr=2e-5, eps=1e-8
optim = torch.optim.Adam(classifier.parameters(), lr=2e-5, weight_decay=1e-5)

old_acc = 0
nr_epochs = 60
count = 0
bs = 16
max_doc_len = 80

for epoch in range(nr_epochs):
    for i, (batch, mask, current_pos) in enumerate(get_batch(bs, max_doc_len, train_texts)):
        optim.zero_grad()
        out = classifier.forward(batch, mask)          
        labels = train_labels[current_pos-bs:current_pos]            
        loss = loss_fct(out, torch.tensor(np.array(labels).astype('int')))
        loss.backward()
        optim.step()
    if epoch % 20 == 0:
        print(loss)
            
    # early stopping at the end of every epoch
    acc = 0
    nr_batches = 0
    with torch.no_grad():
        for val_batch, mask, val_current_pos in get_batch(bs, max_doc_len, val_texts):
            out = classifier(val_batch, mask)
            # get max of out
            pred = torch.argmax(out, dim=1)
            acc += (torch.sum(pred == torch.tensor(np.array(val_labels[val_current_pos-bs:val_current_pos]).astype('int'))).item() / bs)
            nr_batches += 1
        acc /= nr_batches
        count +=1
        if acc > old_acc:
            old_acc = acc
            print(acc)
            torch.save(classifier.state_dict(), 'best_model.pth')
            count = 0
        if count > 10:
            # end training
            # break  
            print('Problem') 
            
# TODO can add dropout, weight decay...if training loss decreases, but accuracy does not improve
# we overfit on the training data...

tensor(-0.3069, grad_fn=<NllLossBackward0>)
0.33812111801242234
0.4010093167701863
0.41847826086956524
0.4277950310559006
0.43827639751552794
0.5543478260869565
0.5613354037267081
0.562888198757764
0.5656055900621118
0.5753105590062112
0.5756987577639752
0.5795807453416149


KeyboardInterrupt: 

In [10]:
# Model definition and forward function (5 points): 
# Define the class ClassificationBERTModel as a PyTorch model. 
# In the initialization procedure, the model receives the loaded BERT model 
# and stores it as the model's parameter. 
# The parameters of the BERT model should be trainable. 
# The forward function of the model receives a batch of data, passes this batch to BERT, 
# and achieves the corresponding document embeddings from the output of BERT. 
# Similar to the previous task, the document embeddings are used for classification
# by linearly transforming document embeddings to the vectors with the number of classes, 
# followed by applying Softmax.

class ClassificationBERTModel(nn.Module):
    
    def __init__(self, model, train=True):
        super(ClassificationBERTModel, self).__init__()
        self.model = model # nn.Parameter(model)
        if train:
            self.model.train()
            for param in self.model.parameters():
                param.requires_grad = True
        else:
            self.model.eval()
            for param in self.model.parameters():
                param.requires_grad = False
        # self.model.requires_grad = True
        self.linear = nn.Linear(128,12)# smaller cuz of tiny bert, else it is around 700
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, batch, attention_mask):
        # batch are the input_ids of the texts...
        # out = self.softmax(self.linear(self.model(batch)['pooler_output']))
        # TODO pooler_output???
        # print(self.model(batch)['pooler_output'].shape)
        out = self.softmax(self.linear(self.model(batch, attention_mask)['pooler_output']))
        return out
        
        # print(out['last_hidden_state'].shape, out['pooler_output'].shape)
        
# Training and overall functionality (3 points): 
# Train the model in a similar fashion to the previous task, 
# namely with the proper loss function, optimization, and early stoping.
    
model = BertModel.from_pretrained("bert-base-uncased") 
model = BertModel.from_pretrained("prajjwal1/bert-tiny") 

classifier = ClassificationBERTModel(model)
loss_fct = nn.NLLLoss() # nn.NLLLoss()
# lr=2e-5, eps=1e-8
optim = torch.optim.Adam(classifier.parameters(), lr=2e-5, weight_decay=1e-4)

old_acc = 0
nr_epochs = 60
count = 0
bs = 16
max_doc_len = 80

for epoch in range(nr_epochs):
    for i, (batch, mask, current_pos) in enumerate(get_batch(bs, max_doc_len, train_texts)):
        optim.zero_grad()
        out = classifier.forward(batch, mask)          
        labels = train_labels[current_pos-bs:current_pos]            
        loss = loss_fct(out, torch.tensor(np.array(labels).astype('int')))
        loss.backward()
        optim.step()
    if epoch % 20 == 0:
        print(loss)
            
    # early stopping at the end of every epoch
    acc = 0
    nr_batches = 0
    with torch.no_grad():
        for val_batch, mask, val_current_pos in get_batch(bs, max_doc_len, val_texts):
            out = classifier(val_batch, mask)
            # get max of out
            pred = torch.argmax(out, dim=1)
            acc += (torch.sum(pred == torch.tensor(np.array(val_labels[val_current_pos-bs:val_current_pos]).astype('int'))).item() / bs)
            nr_batches += 1
        acc /= nr_batches
        count +=1
        if acc > old_acc:
            old_acc = acc
            print(acc)
            torch.save(classifier.state_dict(), 'best_model.pth')
            count = 0
        if count > 10:
            # end training
            # break  
            print('Problem') 
            
# TODO can add dropout, weight decay...if training loss decreases, but accuracy does not improve
# we overfit on the training data...

tensor(-0.5557, grad_fn=<NllLossBackward0>)
0.5714285714285714
0.6482919254658385
0.6583850931677019
0.6622670807453416
0.6909937888198758
0.7010869565217391
0.7263198757763976
0.7430124223602484
0.7449534161490683
0.765527950310559
0.7690217391304348
tensor(-0.9336, grad_fn=<NllLossBackward0>)
0.7697981366459627
0.7721273291925466
tensor(-0.9370, grad_fn=<NllLossBackward0>)
Problem


KeyboardInterrupt: 

In [10]:
# Model definition and forward function (5 points): 
# Define the class ClassificationBERTModel as a PyTorch model. 
# In the initialization procedure, the model receives the loaded BERT model 
# and stores it as the model's parameter. 
# The parameters of the BERT model should be trainable. 
# The forward function of the model receives a batch of data, passes this batch to BERT, 
# and achieves the corresponding document embeddings from the output of BERT. 
# Similar to the previous task, the document embeddings are used for classification
# by linearly transforming document embeddings to the vectors with the number of classes, 
# followed by applying Softmax.

class ClassificationBERTModel(nn.Module):
    
    def __init__(self, model, train=True):
        super(ClassificationBERTModel, self).__init__()
        self.model = model # nn.Parameter(model)
        if train:
            self.model.train()
            for param in self.model.parameters():
                param.requires_grad = True
        else:
            self.model.eval()
            for param in self.model.parameters():
                param.requires_grad = False
        # self.model.requires_grad = True
        self.linear = nn.Linear(128,12)# smaller cuz of tiny bert, else it is around 700
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, batch, attention_mask):
        # batch are the input_ids of the texts...
        # out = self.softmax(self.linear(self.model(batch)['pooler_output']))
        # TODO pooler_output???
        # print(self.model(batch)['pooler_output'].shape)
        out = self.linear(self.model(batch, attention_mask)['pooler_output'])
        return out
        
        # print(out['last_hidden_state'].shape, out['pooler_output'].shape)
        
# Training and overall functionality (3 points): 
# Train the model in a similar fashion to the previous task, 
# namely with the proper loss function, optimization, and early stoping.
    
model = BertModel.from_pretrained("bert-base-uncased") 
model = BertModel.from_pretrained("prajjwal1/bert-tiny") 

classifier = ClassificationBERTModel(model)
loss_fct = nn.CrossEntropyLoss() # nn.NLLLoss()
# lr=2e-5, eps=1e-8
optim = torch.optim.SGD(classifier.parameters(), lr=5e-5)

old_acc = 0
nr_epochs = 60
count = 0
bs = 16
max_doc_len = 80

for epoch in range(nr_epochs):
    for i, (batch, mask, current_pos) in enumerate(get_batch(bs, max_doc_len, train_texts)):
        optim.zero_grad()
        out = classifier.forward(batch, mask)          
        labels = train_labels[current_pos-bs:current_pos]            
        loss = loss_fct(out, torch.tensor(np.array(labels).astype('int')))
        loss.backward()
        optim.step()
    if epoch % 20 == 0:
        print(loss)
            
    # early stopping at the end of every epoch
    acc = 0
    nr_batches = 0
    with torch.no_grad():
        for val_batch, mask, val_current_pos in get_batch(bs, max_doc_len, val_texts):
            out = classifier(val_batch, mask)
            # get max of out
            pred = torch.argmax(out, dim=1)
            acc += (torch.sum(pred == torch.tensor(np.array(val_labels[val_current_pos-bs:val_current_pos]).astype('int'))).item() / bs)
            nr_batches += 1
        acc /= nr_batches
        count +=1
        if acc > old_acc:
            old_acc = acc
            print(acc)
            torch.save(classifier.state_dict(), 'best_model.pth')
            count = 0
        if count > 10:
            # end training
            # break  
            print('Problem') 
            
# TODO can add dropout, weight decay...if training loss decreases, but accuracy does not improve
# we overfit on the training data...

tensor(2.1101, grad_fn=<NllLossBackward0>)
0.296583850931677
0.35403726708074534
0.3606366459627329
0.3769409937888199
0.3796583850931677
0.38742236024844723
0.39712732919254656
0.3998447204968944
0.4169254658385093
0.4231366459627329
0.4359472049689441
0.4704968944099379
0.48330745341614906
0.4891304347826087
0.4957298136645963
0.5069875776397516
0.5143633540372671
0.5194099378881988
tensor(1.6919, grad_fn=<NllLossBackward0>)
0.5248447204968945
0.5267857142857143
0.5407608695652174
0.5508540372670807
0.5539596273291926
0.5617236024844721
0.5687111801242236
0.5788043478260869
0.5834627329192547
0.5989906832298136
0.6110248447204969
0.6203416149068323
0.6370341614906833
0.640139751552795
0.6413043478260869
0.6502329192546584
0.6521739130434783
0.6587732919254659
0.6704192546583851
tensor(1.0591, grad_fn=<NllLossBackward0>)
0.671972049689441
0.6750776397515528
0.6843944099378882
0.6890527950310559
0.6894409937888198
0.6964285714285714
0.6975931677018633
0.7041925465838509
0.7061335403726

In [11]:
# Test Set Evaluation (1 point): After finishing the training, 
# load the (already stored) best performing model, 
# and use it for class prediction on the test set.
model = BertModel.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("prajjwal1/bert-tiny") 
classifier = ClassificationBERTModel(model, train=False)
classifier.load_state_dict(torch.load('best_model.pth'))
# classifier.eval()

for test_batch, mask, test_current_pos in get_batch(bs, max_doc_len, test_texts):
        out = classifier(test_batch, mask)
        # get max of out
        pred = torch.argmax(out, dim=1)
        print(pred)
        print(test_labels[test_current_pos-bs:test_current_pos])

# Reporting (1 point): Report the results of the best performing model on 
# the validation and test set in a table.

tensor([4, 4, 3, 9, 9, 1, 3, 3, 3, 4, 4, 3, 9, 9, 2, 4])
['8', '9', '3', '9', '8', '1', '3', '3', '0', '1', '4', '3', '4', '9', '2', '4']
tensor([4, 4, 1, 3, 4, 9, 4, 3, 3, 9, 9, 9, 4, 9, 4, 4])
['4', '4', '1', '5', '4', '9', '4', '5', '3', '0', '9', '9', '4', '9', '4', '4']
tensor([3, 2, 3, 9, 4, 0, 9, 9, 4, 9, 4, 9, 0, 3, 9, 4])
['8', '2', '3', '4', '4', '8', '9', '9', '4', '9', '4', '9', '0', '3', '9', '4']
tensor([2, 1, 3, 9, 3, 9, 0, 9, 1, 4, 9, 9, 4, 4, 0, 4])
['2', '1', '3', '4', '5', '9', '0', '9', '1', '4', '9', '9', '8', '4', '0', '4']
tensor([3, 3, 3, 8, 2, 4, 3, 9, 0, 9, 9, 4, 9, 4, 0, 4])
['3', '7', '3', '8', '2', '4', '3', '9', '9', '1', '9', '4', '0', '4', '9', '4']
tensor([9, 0, 3, 9, 0, 1, 1, 3, 0, 9, 3, 0, 9, 4, 9, 4])
['9', '0', '3', '9', '9', '1', '9', '3', '2', '9', '3', '9', '9', '4', '5', '4']
tensor([9, 4, 9, 4, 9, 0, 3, 1, 3, 4, 4, 2, 4, 1, 3, 3])
['9', '4', '9', '4', '6', '0', '3', '0', '3', '4', '4', '2', '1', '1', '3', '3']
tensor([4, 2, 3, 1, 4, 1, 0, 4, 9,

KeyboardInterrupt: 